import { stubGet, stubPost } from './wiremock'

export default {
  stubActivitiesAndAppointmentsPing: () => stubGet('/activities-and-appointments-api/health/ping'),
  stubIsAppointmentsRolledOut: () => stubGet('/activities-and-appointments-api/rollout/MDI', { prisonLive: true }),
  stubGetAppointments: () =>
    stubPost('/activities-and-appointments-api/appointments/MDI/search', [
      {
        id: 37823,
        appointmentId: 3194,
        attendees: [{ prisonerNumber: 'G9566GQ' }],
        category: { code: 'VLB', description: 'Video Link - Court Hearing' },
        offenderNo: 'G9566GQ',
        date: '2025-07-18',
        startTime: '09:45',
        endTime: '10:00',
        appointmentTypeCode: 'VLB',
        appointmentTypeDescription: 'Video Link - Court Hearing',
        locationId: 67126,
        locationDescription: 'A Wing Video Link',
        status: 'ACTIVE',
        viewAppointmentLink: 'https://test-gov.uk/37823',
        createdTime: '2025-07-15T11:44:34',
        updatedTime: null,
        cancelledTime: null,
        cancelledBy: null,
      },
      {
        id: 37782,
        appointmentId: 3195,
        attendees: [{ prisonerNumber: 'G9566GQ' }],
        category: { code: 'VLB', description: 'Video Link - Court Hearing' },
        offenderNo: 'G9566GQ',
        date: '2025-07-18',
        startTime: '10:00',
        endTime: '11:00',
        appointmentTypeCode: 'VLB',
        appointmentTypeDescription: 'Video Link - Court Hearing',
        locationId: 67126,
        locationDescription: 'A Wing Video Link',
        status: 'ACTIVE',
        viewAppointmentLink: 'https://test-gov.uk/37782',
        createdTime: '2025-07-04T12:03:47',
        updatedTime: '2025-07-04T12:04:44',
        cancelledTime: null,
        cancelledBy: null,
      },
      {
        id: 37824,
        appointmentId: 3196,
        attendees: [{ prisonerNumber: 'G9566GQ' }],
        category: { code: 'VLB', description: 'Video Link - Court Hearing' },
        offenderNo: 'G9566GQ',
        date: '2025-07-18',
        startTime: '11:00',
        endTime: '11:15',
        appointmentTypeCode: 'VLB',
        appointmentTypeDescription: 'Video Link - Court Hearing',
        locationId: 67126,
        locationDescription: 'A Wing Video Link',
        status: 'ACTIVE',
        viewAppointmentLink: 'https://test-gov.uk/37824',
        createdTime: '2025-07-15T11:44:34',
        updatedTime: null,
        cancelledTime: null,
        cancelledBy: null,
      },
    ]),
  stubGetAppointmentCategories: () =>
    stubGet('/activities-and-appointments-api/appointment-categories', [
      {
        code: 'VLB',
        description: 'Video Link - Court Hearing',
      },
      {
        code: 'VLPM',
        description: 'Video Link - Probation Meeting',
      },
    ]),
}
