import { stubGet } from './wiremock'

export default {
  stubBookAVideoLinkPing: () => stubGet('/book-a-video-link-api/health/ping'),
  stubGetVideoLinkBookings: () =>
    stubGet('/book-a-video-link-api/schedule/prison/MDI\\?date=(.)*&includeCancelled=true', [
      {
        videoBookingId: 1292,
        prisonAppointmentId: 3194,
        bookingType: 'COURT',
        statusCode: 'ACTIVE',
        videoUrl: 'https://test-gov.uk',
        createdByPrison: false,
        courtId: 304,
        courtCode: 'ABERCV',
        courtDescription: 'Aberystwyth Civil',
        hearingType: 'APPEAL',
        hearingTypeDescription: 'Appeal',
        probationTeamId: null,
        probationTeamCode: null,
        probationTeamDescription: null,
        probationMeetingType: null,
        probationMeetingTypeDescription: null,
        prisonCode: 'MDI',
        prisonerNumber: 'G9566GQ',
        appointmentType: 'VLB_COURT_PRE',
        appointmentTypeDescription: 'Video link booking - pre hearing',
        prisonLocKey: 'MDI-RES-AWING-AWVL',
        prisonLocDesc: 'A Wing Video Link',
        dpsLocationId: '1c7d77da-3193-45ef-81a9-1e2f4d9ad54e',
        appointmentDate: '2025-07-18',
        startTime: '09:45',
        endTime: '10:00',
        createdTime: '2025-07-04T12:03:46.068391',
        updatedTime: '2025-07-15T11:44:31.476393',
        probationOfficerName: null,
        probationOfficerEmailAddress: null,
        notesForStaff: 'staff notes',
        notesForPrisoners: 'notes for prisoner',
        hmctsNumber: null,
        guestPin: null,
      },
      {
        videoBookingId: 1292,
        prisonAppointmentId: 3195,
        bookingType: 'COURT',
        statusCode: 'ACTIVE',
        videoUrl: null,
        createdByPrison: false,
        courtId: 304,
        courtCode: 'ABERCV',
        courtDescription: 'Aberystwyth Civil',
        hearingType: 'APPEAL',
        hearingTypeDescription: 'Appeal',
        probationTeamId: null,
        probationTeamCode: null,
        probationTeamDescription: null,
        probationMeetingType: null,
        probationMeetingTypeDescription: null,
        prisonCode: 'MDI',
        prisonerNumber: 'G9566GQ',
        appointmentType: 'VLB_COURT_MAIN',
        appointmentTypeDescription: 'Video link booking - hearing',
        prisonLocKey: 'MDI-RES-AWING-AWVL',
        prisonLocDesc: 'A Wing Video Link',
        dpsLocationId: '1c7d77da-3193-45ef-81a9-1e2f4d9ad54e',
        appointmentDate: '2025-07-18',
        startTime: '10:00',
        endTime: '11:00',
        createdTime: '2025-07-04T12:03:46.068391',
        updatedTime: '2025-07-15T11:44:31.476393',
        probationOfficerName: null,
        probationOfficerEmailAddress: null,
        notesForStaff: 'staff notes',
        notesForPrisoners: 'notes for prisoner',
        hmctsNumber: null,
        guestPin: '4567',
      },
      {
        videoBookingId: 1292,
        prisonAppointmentId: 3196,
        bookingType: 'COURT',
        statusCode: 'ACTIVE',
        videoUrl: 'https://test-gov.uk',
        createdByPrison: false,
        courtId: 304,
        courtCode: 'ABERCV',
        courtDescription: 'Aberystwyth Civil',
        hearingType: 'APPEAL',
        hearingTypeDescription: 'Appeal',
        probationTeamId: null,
        probationTeamCode: null,
        probationTeamDescription: null,
        probationMeetingType: null,
        probationMeetingTypeDescription: null,
        prisonCode: 'MDI',
        prisonerNumber: 'G9566GQ',
        appointmentType: 'VLB_COURT_POST',
        appointmentTypeDescription: 'Video link booking - post hearing',
        prisonLocKey: 'MDI-RES-AWING-AWVL',
        prisonLocDesc: 'A Wing Video Link',
        dpsLocationId: '1c7d77da-3193-45ef-81a9-1e2f4d9ad54e',
        appointmentDate: '2025-07-18',
        startTime: '11:00',
        endTime: '11:15',
        createdTime: '2025-07-04T12:03:46.068391',
        updatedTime: '2025-07-15T11:44:31.476393',
        probationOfficerName: null,
        probationOfficerEmailAddress: null,
        notesForStaff: 'staff notes',
        notesForPrisoners: 'notes for prisoner',
        hmctsNumber: null,
        guestPin: null,
      },
    ]),
  stubGetCourts: () => stubGet('/book-a-video-link-api/courts', []),
  stubGetProbationTeams: () => stubGet('/book-a-video-link-api/probation-teams', []),
}
